# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateVirtualEntityRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, information: str=None):  # noqa: E501
        """CreateVirtualEntityRequest - a model defined in Swagger

        :param title: The title of this CreateVirtualEntityRequest.  # noqa: E501
        :type title: str
        :param description: The description of this CreateVirtualEntityRequest.  # noqa: E501
        :type description: str
        :param information: The information of this CreateVirtualEntityRequest.  # noqa: E501
        :type information: str
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            'information': str
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            'information': 'information'
        }
        self._title = title
        self._description = description
        self._information = information

    @classmethod
    def from_dict(cls, dikt) -> 'CreateVirtualEntityRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createVirtualEntityRequest of this CreateVirtualEntityRequest.  # noqa: E501
        :rtype: CreateVirtualEntityRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this CreateVirtualEntityRequest.


        :return: The title of this CreateVirtualEntityRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this CreateVirtualEntityRequest.


        :param title: The title of this CreateVirtualEntityRequest.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this CreateVirtualEntityRequest.


        :return: The description of this CreateVirtualEntityRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CreateVirtualEntityRequest.


        :param description: The description of this CreateVirtualEntityRequest.
        :type description: str
        """

        self._description = description

    @property
    def information(self) -> str:
        """Gets the information of this CreateVirtualEntityRequest.


        :return: The information of this CreateVirtualEntityRequest.
        :rtype: str
        """
        return self._information

    @information.setter
    def information(self, information: str):
        """Sets the information of this CreateVirtualEntityRequest.


        :param information: The information of this CreateVirtualEntityRequest.
        :type information: str
        """

        self._information = information
