# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateLessonRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, description: str=None, _date: datetime=None):  # noqa: E501
        """CreateLessonRequest - a model defined in Swagger

        :param title: The title of this CreateLessonRequest.  # noqa: E501
        :type title: str
        :param description: The description of this CreateLessonRequest.  # noqa: E501
        :type description: str
        :param _date: The _date of this CreateLessonRequest.  # noqa: E501
        :type _date: datetime
        """
        self.swagger_types = {
            'title': str,
            'description': str,
            '_date': datetime
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description',
            '_date': 'date'
        }
        self._title = title
        self._description = description
        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'CreateLessonRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createLessonRequest of this CreateLessonRequest.  # noqa: E501
        :rtype: CreateLessonRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this CreateLessonRequest.


        :return: The title of this CreateLessonRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this CreateLessonRequest.


        :param title: The title of this CreateLessonRequest.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this CreateLessonRequest.


        :return: The description of this CreateLessonRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this CreateLessonRequest.


        :param description: The description of this CreateLessonRequest.
        :type description: str
        """

        self._description = description

    @property
    def _date(self) -> datetime:
        """Gets the _date of this CreateLessonRequest.


        :return: The _date of this CreateLessonRequest.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this CreateLessonRequest.


        :param _date: The _date of this CreateLessonRequest.
        :type _date: datetime
        """

        self.__date = _date
