# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Lesson(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, subject_id: int=None, description: str=None, title: str=None, _date: datetime=None):  # noqa: E501
        """Lesson - a model defined in Swagger

        :param id: The id of this Lesson.  # noqa: E501
        :type id: int
        :param subject_id: The subject_id of this Lesson.  # noqa: E501
        :type subject_id: int
        :param description: The description of this Lesson.  # noqa: E501
        :type description: str
        :param title: The title of this Lesson.  # noqa: E501
        :type title: str
        :param _date: The _date of this Lesson.  # noqa: E501
        :type _date: datetime
        """
        self.swagger_types = {
            'id': int,
            'subject_id': int,
            'description': str,
            'title': str,
            '_date': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'subject_id': 'subjectId',
            'description': 'description',
            'title': 'title',
            '_date': 'date'
        }
        self._id = id
        self._subject_id = subject_id
        self._description = description
        self._title = title
        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'Lesson':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Lesson of this Lesson.  # noqa: E501
        :rtype: Lesson
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Lesson.


        :return: The id of this Lesson.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Lesson.


        :param id: The id of this Lesson.
        :type id: int
        """

        self._id = id

    @property
    def subject_id(self) -> int:
        """Gets the subject_id of this Lesson.


        :return: The subject_id of this Lesson.
        :rtype: int
        """
        return self._subject_id

    @subject_id.setter
    def subject_id(self, subject_id: int):
        """Sets the subject_id of this Lesson.


        :param subject_id: The subject_id of this Lesson.
        :type subject_id: int
        """

        self._subject_id = subject_id

    @property
    def description(self) -> str:
        """Gets the description of this Lesson.


        :return: The description of this Lesson.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Lesson.


        :param description: The description of this Lesson.
        :type description: str
        """

        self._description = description

    @property
    def title(self) -> str:
        """Gets the title of this Lesson.


        :return: The title of this Lesson.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Lesson.


        :param title: The title of this Lesson.
        :type title: str
        """

        self._title = title

    @property
    def _date(self) -> datetime:
        """Gets the _date of this Lesson.


        :return: The _date of this Lesson.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this Lesson.


        :param _date: The _date of this Lesson.
        :type _date: datetime
        """

        self.__date = _date
