# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Lesson(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, lesson_id: int=None, subject_id: int=None, lesson_description: str=None, lesson_title: str=None, _date: datetime=None):  # noqa: E501
        """Lesson - a model defined in Swagger

        :param lesson_id: The lesson_id of this Lesson.  # noqa: E501
        :type lesson_id: int
        :param subject_id: The subject_id of this Lesson.  # noqa: E501
        :type subject_id: int
        :param lesson_description: The lesson_description of this Lesson.  # noqa: E501
        :type lesson_description: str
        :param lesson_title: The lesson_title of this Lesson.  # noqa: E501
        :type lesson_title: str
        :param _date: The _date of this Lesson.  # noqa: E501
        :type _date: datetime
        """
        self.swagger_types = {
            'lesson_id': int,
            'subject_id': int,
            'lesson_description': str,
            'lesson_title': str,
            '_date': datetime
        }

        self.attribute_map = {
            'lesson_id': 'lesson_id',
            'subject_id': 'subject_id',
            'lesson_description': 'lesson_description',
            'lesson_title': 'lesson_title',
            '_date': 'date'
        }
        self._lesson_id = lesson_id
        self._subject_id = subject_id
        self._lesson_description = lesson_description
        self._lesson_title = lesson_title
        self.__date = _date

    @classmethod
    def from_dict(cls, dikt) -> 'Lesson':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Lesson of this Lesson.  # noqa: E501
        :rtype: Lesson
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lesson_id(self) -> int:
        """Gets the lesson_id of this Lesson.


        :return: The lesson_id of this Lesson.
        :rtype: int
        """
        return self._lesson_id

    @lesson_id.setter
    def lesson_id(self, lesson_id: int):
        """Sets the lesson_id of this Lesson.


        :param lesson_id: The lesson_id of this Lesson.
        :type lesson_id: int
        """

        self._lesson_id = lesson_id

    @property
    def subject_id(self) -> int:
        """Gets the subject_id of this Lesson.


        :return: The subject_id of this Lesson.
        :rtype: int
        """
        return self._subject_id

    @subject_id.setter
    def subject_id(self, subject_id: int):
        """Sets the subject_id of this Lesson.


        :param subject_id: The subject_id of this Lesson.
        :type subject_id: int
        """

        self._subject_id = subject_id

    @property
    def lesson_description(self) -> str:
        """Gets the lesson_description of this Lesson.


        :return: The lesson_description of this Lesson.
        :rtype: str
        """
        return self._lesson_description

    @lesson_description.setter
    def lesson_description(self, lesson_description: str):
        """Sets the lesson_description of this Lesson.


        :param lesson_description: The lesson_description of this Lesson.
        :type lesson_description: str
        """

        self._lesson_description = lesson_description

    @property
    def lesson_title(self) -> str:
        """Gets the lesson_title of this Lesson.


        :return: The lesson_title of this Lesson.
        :rtype: str
        """
        return self._lesson_title

    @lesson_title.setter
    def lesson_title(self, lesson_title: str):
        """Sets the lesson_title of this Lesson.


        :param lesson_title: The lesson_title of this Lesson.
        :type lesson_title: str
        """

        self._lesson_title = lesson_title

    @property
    def _date(self) -> datetime:
        """Gets the _date of this Lesson.


        :return: The _date of this Lesson.
        :rtype: datetime
        """
        return self.__date

    @_date.setter
    def _date(self, _date: datetime):
        """Sets the _date of this Lesson.


        :param _date: The _date of this Lesson.
        :type _date: datetime
        """

        self.__date = _date
