# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Quiz(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None):  # noqa: E501
        """Quiz - a model defined in Swagger

        :param id: The id of this Quiz.  # noqa: E501
        :type id: int
        :param title: The title of this Quiz.  # noqa: E501
        :type title: str
        """
        self.swagger_types = {
            'id': int,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title'
        }
        self._id = id
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'Quiz':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Quiz of this Quiz.  # noqa: E501
        :rtype: Quiz
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Quiz.


        :return: The id of this Quiz.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Quiz.


        :param id: The id of this Quiz.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Quiz.


        :return: The title of this Quiz.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Quiz.


        :param title: The title of this Quiz.
        :type title: str
        """

        self._title = title
