# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Quiz(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, quiz_id: int=None, quiz_name: str=None):  # noqa: E501
        """Quiz - a model defined in Swagger

        :param quiz_id: The quiz_id of this Quiz.  # noqa: E501
        :type quiz_id: int
        :param quiz_name: The quiz_name of this Quiz.  # noqa: E501
        :type quiz_name: str
        """
        self.swagger_types = {
            'quiz_id': int,
            'quiz_name': str
        }

        self.attribute_map = {
            'quiz_id': 'quiz_id',
            'quiz_name': 'quiz_name'
        }
        self._quiz_id = quiz_id
        self._quiz_name = quiz_name

    @classmethod
    def from_dict(cls, dikt) -> 'Quiz':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Quiz of this Quiz.  # noqa: E501
        :rtype: Quiz
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quiz_id(self) -> int:
        """Gets the quiz_id of this Quiz.


        :return: The quiz_id of this Quiz.
        :rtype: int
        """
        return self._quiz_id

    @quiz_id.setter
    def quiz_id(self, quiz_id: int):
        """Sets the quiz_id of this Quiz.


        :param quiz_id: The quiz_id of this Quiz.
        :type quiz_id: int
        """

        self._quiz_id = quiz_id

    @property
    def quiz_name(self) -> str:
        """Gets the quiz_name of this Quiz.


        :return: The quiz_name of this Quiz.
        :rtype: str
        """
        return self._quiz_name

    @quiz_name.setter
    def quiz_name(self, quiz_name: str):
        """Sets the quiz_name of this Quiz.


        :param quiz_name: The quiz_name of this Quiz.
        :type quiz_name: str
        """

        self._quiz_name = quiz_name
