# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Subject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, description: str=None, title: str=None):  # noqa: E501
        """Subject - a model defined in Swagger

        :param id: The id of this Subject.  # noqa: E501
        :type id: int
        :param description: The description of this Subject.  # noqa: E501
        :type description: str
        :param title: The title of this Subject.  # noqa: E501
        :type title: str
        """
        self.swagger_types = {
            'id': int,
            'description': str,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'title': 'title'
        }
        self._id = id
        self._description = description
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'Subject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Subject of this Subject.  # noqa: E501
        :rtype: Subject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Subject.


        :return: The id of this Subject.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Subject.


        :param id: The id of this Subject.
        :type id: int
        """

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this Subject.


        :return: The description of this Subject.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Subject.


        :param description: The description of this Subject.
        :type description: str
        """

        self._description = description

    @property
    def title(self) -> str:
        """Gets the title of this Subject.


        :return: The title of this Subject.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Subject.


        :param title: The title of this Subject.
        :type title: str
        """

        self._title = title
