# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VirtualEntity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, description: str=None, information: str=None, object_model_id: int=None, quiz_id: int=None):  # noqa: E501
        """VirtualEntity - a model defined in Swagger

        :param id: The id of this VirtualEntity.  # noqa: E501
        :type id: int
        :param title: The title of this VirtualEntity.  # noqa: E501
        :type title: str
        :param description: The description of this VirtualEntity.  # noqa: E501
        :type description: str
        :param information: The information of this VirtualEntity.  # noqa: E501
        :type information: str
        :param object_model_id: The object_model_id of this VirtualEntity.  # noqa: E501
        :type object_model_id: int
        :param quiz_id: The quiz_id of this VirtualEntity.  # noqa: E501
        :type quiz_id: int
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'description': str,
            'information': str,
            'object_model_id': int,
            'quiz_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'description': 'description',
            'information': 'information',
            'object_model_id': 'objectModelId',
            'quiz_id': 'quizId'
        }
        self._id = id
        self._title = title
        self._description = description
        self._information = information
        self._object_model_id = object_model_id
        self._quiz_id = quiz_id

    @classmethod
    def from_dict(cls, dikt) -> 'VirtualEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VirtualEntity of this VirtualEntity.  # noqa: E501
        :rtype: VirtualEntity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this VirtualEntity.


        :return: The id of this VirtualEntity.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this VirtualEntity.


        :param id: The id of this VirtualEntity.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this VirtualEntity.


        :return: The title of this VirtualEntity.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this VirtualEntity.


        :param title: The title of this VirtualEntity.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this VirtualEntity.


        :return: The description of this VirtualEntity.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this VirtualEntity.


        :param description: The description of this VirtualEntity.
        :type description: str
        """

        self._description = description

    @property
    def information(self) -> str:
        """Gets the information of this VirtualEntity.


        :return: The information of this VirtualEntity.
        :rtype: str
        """
        return self._information

    @information.setter
    def information(self, information: str):
        """Sets the information of this VirtualEntity.


        :param information: The information of this VirtualEntity.
        :type information: str
        """

        self._information = information

    @property
    def object_model_id(self) -> int:
        """Gets the object_model_id of this VirtualEntity.


        :return: The object_model_id of this VirtualEntity.
        :rtype: int
        """
        return self._object_model_id

    @object_model_id.setter
    def object_model_id(self, object_model_id: int):
        """Sets the object_model_id of this VirtualEntity.


        :param object_model_id: The object_model_id of this VirtualEntity.
        :type object_model_id: int
        """

        self._object_model_id = object_model_id

    @property
    def quiz_id(self) -> int:
        """Gets the quiz_id of this VirtualEntity.


        :return: The quiz_id of this VirtualEntity.
        :rtype: int
        """
        return self._quiz_id

    @quiz_id.setter
    def quiz_id(self, quiz_id: int):
        """Sets the quiz_id of this VirtualEntity.


        :param quiz_id: The quiz_id of this VirtualEntity.
        :type quiz_id: int
        """

        self._quiz_id = quiz_id
