version: '3'
services:
    edugo-server:
        container_name: edugo_server_container
        build: ./backend
        command: sh -c "npm install && npm run dev"
        environment:
            PORT: 7000
            DB_USER: edugo
            DB_PASSWORD: edugo_admin
        ports:
            - '8080:7000'
        working_dir: /usr/app
        volumes:
            - ./backend:/usr/app
        depends_on:
            - db
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: edugo@edugo.com
            PGADMIN_DEFAULT_PASSWORD: edugo_admin
        ports:
            - '8081:80'
    db:
        container_name: postgres_container
        image: postgres
        environment: 
            POSTGRES_USER: edugo
            POSTGRES_PASSWORD: edugo_admin
        ports:
            - '5432:5432'
        volumes:
            - edugo-db:/var/lib/postgresql/data
volumes:
    edugo-db: