openapi: '3.0.2'
info:
  title: EduGo
  description: The swagger API specification for the EduGo API
  version: '1.0'
servers:
  - url: http://localhost:8080
tags:
  - name: Virtual Entity
  - name: Subject
  - name: Lesson
paths:
  /virtualEntity/createVirtualEntity:
    post:
      tags:
        - Virtual Entity
      summary: Create a new virtual entity
      description: ""
      operationId: createVirtualEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateVirtualEntityRequest'
      responses:
        200:
          description: New virtual entity successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateVirtualEntityResponse'
        400:
          description: There was an error

  /virtualEntity/model/uploadModel:
    post:
      tags:
        - Virtual Entity
      summary: Upload a model
      operationId: uploadModel
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Successfully uploaded file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadModelResponse'
        400:
          description: There was an error uploading the file

  /virtualEntity/getVirtualEntities:
    post:
      tags:
        - Virtual Entity
      summary: Get all the virtual entities
      operationId: getVirtualEntities
      responses:
        200:
          description: Successfully sent all virtual entities
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVirtualEntitiesResponse'
        400:
          description: There was an error

  /virtualEntity/getVirtualEntity:
    post:
      tags:
        - Virtual Entity
      summary: Get one virtual entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetVirtualEntityRequest'
      responses:
        200:
          description: Virtual entity successfully found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVirtualEntityResponse'
        400:
          description: Virtual entity could not be found

  /virtualEntity/model/addToVirtualEntity:
    post:
      tags:
        - Virtual Entity
      summary: Add a model to a virtual entity
      operationId: addModelToVirtualEntity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddModelToVirtualEntityRequest'
      responses:
        200:
          description: Successfully added model to virtual entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddModelToVirtualEntityResponse'
        400:
          description: There was an error

components:
  schemas:
    Question:
      type: object
      required:
        - type
        - question
      properties:
        type:
          type: string
        question:
          type: string
        options:
          type: array
          items:
            type: string
        correctAnswer:
          type: string
    
    Quiz:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'

    Model:
      type: object
      required:
        - name
        - description
        - file_link
        - file_size
        - file_name
        - file_type
      properties:
        name:
          type: string
        description:
          type: string
        file_link:
          type: string
        file_size:
          type: number
          format: int32
        file_name:
          type: string
        file_type:
          type: string
        preview_img:
          type: string

    GVEs_Model:
      type: object
      properties:
        id:
          type: number
          format: int64
        name:
          type: string
        description:
          type: string
        file_link:
          type: string
        file_size:
          type: number
          format: int64
        file_type:
          type: string
        file_name:
          type: string

    GVE_Model:
      type: object
      properties:
        id:
          type: number
          format: int64
        name:
          type: string
        description:
          type: string
        file_link:
          type: string
        file_size:
          type: number
          format: int64
        file_type:
          type: string
        file_name:
          type: string

    GVE_Quiz:
      type: object
      required:
        - title
        - description
      properties:
        id:
          type: number
          format: int64
        title:
          type: string
        description:
          type: string
        questions:
          type: array
          items:
            $ref: '#/components/schemas/GVE_Question'

    GVE_Question:
      type: object
      required:
        - type
        - question
      properties:
        id:
          type: number
          format: int64
        type:
          type: string
        question:
          type: string
        options:
          type: array
          items:
            type: string
        correctAnswer:
          type: string

    CreateVirtualEntityRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        quiz:
          $ref: '#/components/schemas/Quiz'
        model:
          $ref: '#/components/schemas/Model'
    
    CreateVirtualEntityResponse:
      type: object
      properties:
        id:
          type: number
          format: int64
        message:
          type: string

    GetVirtualEntitiesResponse:
      type: object
      properties:
        entities:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                format: int64
              title:
                type: string
              description:
                type: string
              model:
                $ref: '#/components/schemas/GVEs_Model'

    GetVirtualEntityRequest:
      type: object
      properties:
        id:
          type: number
          format: int64

    GetVirtualEntityResponse:
      type: object
      properties:
        id:
          type: number
          format: int64
        title:
          type: string
        description:
          type: string
        quiz:
          $ref: '#/components/schemas/GVE_Quiz'
        model:
          $ref: '#/components/schemas/GVE_Model'

    AddModelToVirtualEntityRequest:
      type: object
      properties:
        'virtualEntity_id':
          type: number
          format: int64
        name:
          type: string
        description:
          type: string
        
    AddModelToVirtualEntityResponse:
      type: object
      properties:
        'virtualEntity_id':
          type: number
          format: int64
        'model_id':
          type: number
          format: int64
        name:
          type: string
        description:
          type: string
        file_link:
          type: string
        file_size:
          type: number
          format: int64
        file_type:
          type: string
        file_name:
          type: string
        
    UploadModelResponse:
      type: object
      properties:
        file_link:
          type: string
        file_size:
          type: number
          format: int64
        file_type:
          type: string
        file_name:
          type: string

        