# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Model3DModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _3d_model_id: int=None, _3d_model_name: str=None):  # noqa: E501
        """Model3DModel - a model defined in Swagger

        :param _3d_model_id: The _3d_model_id of this Model3DModel.  # noqa: E501
        :type _3d_model_id: int
        :param _3d_model_name: The _3d_model_name of this Model3DModel.  # noqa: E501
        :type _3d_model_name: str
        """
        self.swagger_types = {
            '_3d_model_id': int,
            '_3d_model_name': str
        }

        self.attribute_map = {
            '_3d_model_id': '3d_model_id',
            '_3d_model_name': '3d_model_name'
        }
        self.__3d_model_id = _3d_model_id
        self.__3d_model_name = _3d_model_name

    @classmethod
    def from_dict(cls, dikt) -> 'Model3DModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The 3D_Model of this Model3DModel.  # noqa: E501
        :rtype: Model3DModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _3d_model_id(self) -> int:
        """Gets the _3d_model_id of this Model3DModel.


        :return: The _3d_model_id of this Model3DModel.
        :rtype: int
        """
        return self.__3d_model_id

    @_3d_model_id.setter
    def _3d_model_id(self, _3d_model_id: int):
        """Sets the _3d_model_id of this Model3DModel.


        :param _3d_model_id: The _3d_model_id of this Model3DModel.
        :type _3d_model_id: int
        """

        self.__3d_model_id = _3d_model_id

    @property
    def _3d_model_name(self) -> str:
        """Gets the _3d_model_name of this Model3DModel.


        :return: The _3d_model_name of this Model3DModel.
        :rtype: str
        """
        return self.__3d_model_name

    @_3d_model_name.setter
    def _3d_model_name(self, _3d_model_name: str):
        """Sets the _3d_model_name of this Model3DModel.


        :param _3d_model_name: The _3d_model_name of this Model3DModel.
        :type _3d_model_name: str
        """

        self.__3d_model_name = _3d_model_name
