openapi: 3.0.0
info:
  title: EduGo Api
  description: 'Api for the EduGo sytsem '
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Gang-of-Five/EduGo/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost:8080
  description: localhost server
tags:
- name: lesson
  description: Subsystem for lessons
- name: virtualEntity
  description: Subsystem for virtual entity which includes 3d model and information
- name: subject
  description: Subsystem for a subject
paths:
  /lesson/createLesson:
    post:
      tags:
      - lesson
      summary: Create a lesson for a subject
      operationId: create_lesson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createLessonRequest'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "405":
          description: Invalid parameters
      x-openapi-router-controller: swagger_server.controllers.lesson_controller
  /virtualEntity/createVirtualEntity:
    post:
      tags:
      - virtualEntity
      summary: Create virtual entity for lesson
      operationId: create_virtual_entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createVirtualEntityRequest'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "405":
          description: Invalid parameters
      x-openapi-router-controller: swagger_server.controllers.virtual_entity_controller
  /subject/createSubject:
    post:
      tags:
      - subject
      summary: Create subject for organization
      operationId: create_subject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createSubjectRequest'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        "405":
          description: Invalid parameters
      x-openapi-router-controller: swagger_server.controllers.subject_controller
components:
  schemas:
    Lesson:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subjectId:
          type: integer
          format: int64
        description:
          type: string
        title:
          type: string
        date:
          type: string
          format: date-time
    Subject:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        title:
          type: string
    VirtualEntity:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        information:
          type: string
        objectModelId:
          type: integer
          format: int64
        quizId:
          type: integer
          format: int64
    ObjectModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Quiz:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
    Question:
      type: object
      properties:
        id:
          type: integer
          format: int64
        question:
          type: string
        options:
          $ref: '#/components/schemas/TFQuestion'
        answer:
          type: boolean
    createLessonRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date-time
    createSubjectRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
    createVirtualEntityRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        information:
          type: string
    ApiResponse:
      type: object
      properties:
        message:
          type: string
      example:
        message: message
    TFQuestion:
      type: string
      enum:
      - "true"
      - "false"

