name: API Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm ci
              working-directory: ./backend
            #- run: docker-compose run --rm edugo-server npm run test
            - run: npm test
              working-directory: ./backend
            - uses: SonarSource/sonarcloud-github-action@master
